server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&rewriteBatchedStatements=true #rewriteBatchedStatements=true 开启批处理
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root   #密文要以mpw:开头
    password: 123456
#    username: mpw:+XP/ExRR+Gb3eguFKAxaFg==   #密文要以mpw:开头
#    password: mpw:Q3K9CGl9VeojgI1RO4UmCQ==
logging:
  level:
    com.clb: debug
  pattern:
    dateformat: HH:mm:ss

# mybatis-plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志输出
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler  #枚举处理器
  type-aliases-package: com.clb.domain.pojo
  global-config:
    db-config:
      id-type: auto   # 主键id生成策略
      logic-delete-field: isDefault #逻辑删除字段

